version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/postgres
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    ports:
      - "8081:80" # Nginx는 기본적으로 80 포트를 사용합니다.
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ./frontend:/app
      - /app/node_modules


  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
