version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web: #backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    depends_on:

      - db
      - redis
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"  # 호스트 포트와 컨테이너 포트를 매핑합니다.




  frontend:
    ports:
      - "8081:80" # Nginx는 기본적으로 80 포트를 사용합니다.
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    volumes:
      - ./frontend:/app
      - /app/node_modules


  db:
    image: postgres:16.0-alpine
    ports:
      - "5432:5432" # 호스트 포트와 컨테이너 포트를 매핑합니다.
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ~/work_space/react-fastapi/pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
